### ISSUE TITLE
Conflict with Gitlens

### ISSUE THREAD

**Issue by laakal** [mtbaqer/vscode-better-folding#12]
https://user-images.githubusercontent.com/9221304/215426035-e4d11463-854c-4488-9482-36fa829114d4.mov

**Comment by mtbaqer** [comment]
Interesting bug. Thanks for reporting it. Might take a bit to fix to be totally honest given how the extension works, but will look into a fix.

To also gather opinions, what would you say the better solution:
- Hiding the gitlens text on fold
Or
- keep it but potentially let the text overflow to the right?

**Comment by laakal** [comment]
Thanks @mtbaqer. it would be nice to hide the gitlens text on fold.

**Comment by mtbaqer** [comment]
Requires https://github.com/microsoft/vscode/issues/172881. Should be able to fix it if the PR is merged.
