### ISSUE TITLE
Folded text is nearly invisible with theme Ayu Light

### ISSUE THREAD

**Issue by RaddishIoW** [mtbaqer/vscode-better-folding#19]
**Describe the bug**
When using the theme [Ayu](https://marketplace.visualstudio.com/items?itemName=teabyii.ayu) Light, the "comments" on the folded line are nearly invisible.

**To Reproduce**
1. Install and activate Ayu Light theme
2. Click on the region to fold
3. Observe text in folded region

**Expected behavior**
You can read the text in the folded region.

**Screenshots**
https://user-images.githubusercontent.com/7757254/216602548-8faa3b3a-d57b-4313-abf4-521e18c5a287.mov

**Desktop (please complete the following information):**
 - OS: macOS 13.2
 - Version v.0.3.0

**Comment by mtbaqer** [comment]
Out of curiosity, how does it look like without the extension?

**Comment by mtbaqer** [comment]
Should be fixed in 0.4.0. Please let me know if this was not that case.
