### ISSUE TITLE
class generic on multi-line

### ISSUE THREAD

**Issue by djmisterjon** [mtbaqer/vscode-better-folding#2]
**To Reproduce**
make structure like this
```ts
export class LocalHistoryESystem extends System<ECSE, [
	MSGTYPES.entity_registred, MSGTYPES.contextmenue_redo, MSGTYPES.contextmenue_undo,
	MSGTYPES.entity_change,
	MSGTYPES.camera_change,
] > {
	static state: 'undo' | 'redo' | null = null;
	constructor() {
		super(
			[UPDATEBEHAVIOR.update],
			[
				[MATCHRULES.hasAll, [LocalHistoryEComponent]],
			],
			[
				MSGTYPES.entity_registred, MSGTYPES.contextmenue_redo, MSGTYPES.contextmenue_undo, MSGTYPES.entity_change, MSGTYPES.camera_change,
			],
		);
	}
}
```

**Expected behavior**
when collapas `LocalHistoryESystem `, only the typescript generic array should collapse, what i we want just hide typescript part  in this case ?

**Screenshots**

**Additional context**

original
![image](https://user-images.githubusercontent.com/24865815/214259047-d6661d8e-1a12-40aa-88a3-e32cdc10fbc5.png)
vscode folding
![image](https://user-images.githubusercontent.com/24865815/214259827-4b253fee-370b-412f-8fd1-3987fb2dbaf8.png)
betterfolding
![image](https://user-images.githubusercontent.com/24865815/214259224-442d28b1-5b60-4ad6-a312-16a31f1d615d.png)

**Comment by mtbaqer** [comment]
Thanks for feedback. I think I have a good solution for this, should be included in the release.

**Comment by mtbaqer** [comment]
Hey this should be resolved by the new release. Now you have an option to disable chaining folding ranges which is what you are describing. 
Can you give it a try and let me if that's what you had in mind?

**Comment by djmisterjon** [comment]
> Hey this should be resolved by the new release. Now you have an option to disable chaining folding ranges which is what you are describing. Can you give it a try and let me if that's what you had in mind?

i will do deep test this night

**Comment by djmisterjon** [comment]
> Hey this should be resolved by the new release. Now you have an option to disable chaining folding ranges which is what you are describing. Can you give it a try and let me if that's what you had in mind?

thank friend your are awsome ! 
work fine 
![image](https://user-images.githubusercontent.com/24865815/215355256-89a15e42-eaba-4e82-a296-c16ebba77ff6.png)
uncheck this opt
![image](https://user-images.githubusercontent.com/24865815/215355283-17052ee1-88cb-4930-a828-f5256f3c11f1.png)
