### ISSUE TITLE
Editing large files with this extension takes a lot of performance resources

### ISSUE THREAD

**Issue by GwnDaan** [mtbaqer/vscode-better-folding#22]
Type: <b>Bug</b>

When editing a relatively large file ~6000 lines, this extension apparently is the cause of a lot of cpu consumption it seems. Which causes VSCode to behave really slow most of the time, e.g. IntelliSense and saving files takes forever. 

Extension version: 0.4.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.16GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Daan/Documents/Development-PC/ISOBUS/ISO11783-CAN-Stack --crash-reporter-id ba8e2d03-84c8-4f01-abf3-0d26248a50da|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
f6dab269:30613381
pythonsymbol12cf:30657549
a9j8j154:30646983
vsccsb:30659829

```

</details>

**Comment by GwnDaan** [comment]
![image](https://user-images.githubusercontent.com/29043784/217514749-59aa8805-65b2-4c16-a41d-9091ddcaae95.png)

**Comment by mtbaqer** [comment]
Thanks for the report, we are tracking the performance problems in #15. Closing this one to limit the duplicates
