### ISSUE TITLE
Installed extension, but it's not doing anything

### ISSUE THREAD

**Issue by eFail** [mtbaqer/vscode-better-folding#6]
**Describe the bug**
I installed the extension.

I expanded/collapsed in a JS file to see if the closing brace would start disappearing, but nothing new happened.  I got the existing experience, where the closing brace stays visible.

I tried closing and reopening VS Code.

I tried disabling and then re-enabling the extension.  

Still nothing.

I checked the settings page for the extension and confirmed everything is turned on.

This extension looks like the greatest thing since sliced bread, but how can I get it to work?

OS: Windows 10 22H2 x64 (19045.2486)
VS Code: 1.74.3
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0

**Comment by mtbaqer** [comment]
Hmm, this is a tough one. I'm not sure what's exactly failing but would you mind a couple of things and see which ones gets it to work?

- Try opening a file with a different language, maybe .ts or . jsx and then try the .js files again.

- Try changing something in the extension settings but don't leave the settings page for 5 seconds then try the .js files.

Yeah apologies for the bug, would more than appreciate it if you could help me to fix it.

**Comment by CertainLach** [comment]
Same for me, there is an error in extension host output:
```
2023-01-29 17:07:49.247 [error] Activating extension MohammadBaqer.better-folding failed due to an error:
2023-01-29 17:07:49.247 [error] Error: Cannot find module './bracketRangesProvider'
Require stack:
- /home/lach/.vscode/extensions/mohammadbaqer.better-folding-0.2.1/out/extension.js
```

**Comment by mtbaqer** [comment]
> Same for me, there is an error in extension host output:
> 
> ```
> 
> 2023-01-29 17:07:49.247 [error] Activating extension MohammadBaqer.better-folding failed due to an error:
> 
> 2023-01-29 17:07:49.247 [error] Error: Cannot find module './bracketRangesProvider'
> 
> Require stack:
> 
> - /home/lach/.vscode/extensions/mohammadbaqer.better-folding-0.2.1/out/extension.js
> 
> ```

Would you mind giving more details on the running conditions? Windows vs Mac, are you running it through an ssh to linux, etc.

**Comment by zakwear** [comment]
Looks like I'm getting the same error as @CertainLach, and I'm running on Ubuntu 22.04.1

> 2023-01-29 08:44:58.530 [error] Activating extension MohammadBaqer.better-folding failed due to an error:
> 2023-01-29 08:44:58.530 [error] Error: Cannot find module './bracketRangesProvider'
> Require stack:
> /home/user/.vscode/extensions/mohammadbaqer.better-folding-0.2.1/out/extension.js
> /snap/code/117/usr/share/code/resources/app/out/vs/loader.js
> /snap/code/117/usr/share/code/resources/app/out/bootstrap-amd.js
>  /snap/code/117/usr/share/code/resources/app/out/bootstrap-fork.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
>     at Module._load (node:internal/modules/cjs/loader:832:27)
>     at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
>     at Function.r._load (/snap/code/117/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
>     at Function.w._load (/snap/code/117/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
>     at Function.v._load (/snap/code/117/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
>     at Module.require (node:internal/modules/cjs/loader:1059:19)
>     at p (/snap/code/117/usr/share/code/resources/app/out/vs/loader.js:4:699)
>     at Object.<anonymous> (/home/user/.vscode/extensions/mohammadbaqer.better-folding-0.2.1/out/extension.js:5:33)
>     at Module.u._compile (/snap/code/117/usr/share/code/resources/app/out/vs/loader.js:4:1313)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
>     at Module.load (node:internal/modules/cjs/loader:1035:32)
>     at Module._load (node:internal/modules/cjs/loader:876:12)
>     at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
>     at Function.r._load (/snap/code/117/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
>     at Function.w._load (/snap/code/117/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
>     at Function.v._load (/snap/code/117/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
>     at Module.require (node:internal/modules/cjs/loader:1059:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Function.r [as __$__nodeRequire] (/snap/code/117/usr/share/code/resources/app/out/vs/loader.js:5:101)
>     at d.pb (/snap/code/117/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:63164)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Promise.all (index 0)

**Comment by zakwear** [comment]
> Hmm, this is a tough one. I'm not sure what's exactly failing but would you mind a couple of things and see which ones gets it to work?
> 
>     * Try opening a file with a different language, maybe .ts or . jsx and then try the .js files again.
> 
>     * Try changing something in the extension settings but don't leave the settings page for 5 seconds then try the .js files.
> 
> 
> Yeah apologies for the bug, would more than appreciate it if you could help me to fix it.

I tried these steps, still got the module not found error.

**Comment by mtbaqer** [comment]
Thanks for following up and for the helping out. Does happen to be on WSL or a normal Ubuntu?

**Comment by CertainLach** [comment]
> Would you mind giving more details on the running conditions? Windows vs Mac, are you running it through an ssh to linux, etc.

Linux (NixOS), running both locally and over ssh remote

**Comment by CertainLach** [comment]
I see, in version published to marketplace, there is file named `BracketRangesProvider.js`, but in `extension.js`, `bracketRangesProvider` is being imported, thus causing failure on case-sensitive fs

**Comment by mtbaqer** [comment]
@CertainLach thanks for the follow up, would you mind trying [this?](https://open-vsx.org/extension/MohammadBaqer/better-folding)

**Comment by CertainLach** [comment]
It works

**Comment by mtbaqer** [comment]
Awesome! Will release it as a patch update. Thanks everyone for reporting the issue.

**Comment by mtbaqer** [comment]
@eFail can you confirm that it works with the last update, so I can close this issue?

**Comment by eFail** [comment]
@mtbaqer 
I tried a .ts file as well as changing settings and waiting 5 seconds.  Still not working unfortunately.  I tried 0.2.2 and 0.2.3, they also don't work.  In my Extension Host output, I don't see any errors being logged.  Anything I can do to help you debug this?

Here's the test file I used (`Foo.ts`):
```ts
class Foo
{
    message: string;
   
    constructor(message: string)
    {
        this.message = message;
    }
   
    output()
    {
        console.log(this.message);
    }
}
let foo = new Foo("Hello world!");
foo.output();
```

Here's what I see after doing a "Fold All":
![image](https://user-images.githubusercontent.com/1672416/215389498-a4a3ecb5-7faf-425f-b908-b3b280f38dd2.png)

**Comment by eFail** [comment]
Interesting.  It does appear to be folding inner ranges.  Just not the function ranges:

Foo.js:
```js
function foo()
{
    {
        console.log("bar");
    }
}
```
This is after "Fold All":
![image](https://user-images.githubusercontent.com/1672416/215390649-b6f07eed-dafb-4b85-aa7b-6d5ed28464ad.png)

And if I then expand the function:
![image](https://user-images.githubusercontent.com/1672416/215390699-8321a98c-98b0-46af-8351-ff58c6d6c091.png)

Folding of the actual functions is what I need the most though.

**Comment by mtbaqer** [comment]
I think I got something. Try [installing this one](https://github.com/mtbaqer/vscode-better-folding/blob/main/better-folding-0.2.4.vsix) and let me know if it works. Of course make sure to delete the original one first.

**Comment by eFail** [comment]
No change :(

![image](https://user-images.githubusercontent.com/1672416/215393364-4082b298-1dd5-44ec-8122-c5867048e619.png)

**Comment by mtbaqer** [comment]
Try to place the curly bracket on the same line as the function name, and see if it works as expected?

**Comment by eFail** [comment]
That did it!  Could the logic easily be updated to support the brace not being on the same line though?  This codebase doesn't use that brace placement everywhere.

**Comment by mtbaqer** [comment]
Yup this is sort of a duplicate of #1. It's trivial to do but definitely a planned feature. See my reply [here](https://github.com/mtbaqer/vscode-better-folding/issues/1).

We can track this problem there, but besides the bracket placement, does everything seems to be working for you?

**Comment by eFail** [comment]
Awesome!  Thank you so much for creating this extension!  I was getting ready to ditch VS Code and switch to Visual Studio for my javascript development because of the way VS Code collapses things, but your extension has made it feasible to stay.  Once #1 is implemented, there will be only one additional feature missing from Visual Studio, and I'll open a feature suggestion for that right now in the hopes that it can easily be added.  Thanks again!
