### ISSUE TITLE
Failed to collapse ending bracket with TypeScript

### ISSUE THREAD

**Issue by joshuaavalon** [mtbaqer/vscode-better-folding#8]
**Describe the bug**
It fails to collapse ending bracket if the language of VSCode is TypeScript.
Same code works if the language is set to JavaScript.

**To Reproduce**
1. Use the code in screenshots
2. Collapse the interface

**Expected behavior**
Collapse ending bracket

**Screenshots**
![image](https://user-images.githubusercontent.com/7152420/215377700-0dfd85f7-fe95-419a-829c-16c9b77fde2b.png)
![image](https://user-images.githubusercontent.com/7152420/215377724-55516eda-5c6d-471e-92ca-637c44f561cc.png)

**Desktop (please complete the following information):**
 - OS: Window 10

**Comment by mtbaqer** [comment]
Can't seem to reproduce this. Did you try reinstalling the extension?

**Comment by mtbaqer** [comment]
Actually, would you mind clean installing [this version ](https://github.com/mtbaqer/vscode-better-folding/blob/main/better-folding-0.2.4.vsix) and let me know if it works for you?

**Comment by joshuaavalon** [comment]
Sorry for troubling you. The issue seems to be fixed after I restart VSCode.
